source 'https://rubygems.org'

gem 'appium_lib'
gem 'appom', '1.2.1', path: './lib_mod/appom-1.2.1'
gem 'browserstack-local'
gem 'cucumber', '~> 3.1.2'
gem 'cucumber-tag_expressions', '~> 1.0'
gem 'data_magic', '0.22'
gem 'dotenv', '~> 2.1', '>= 2.1.1'
gem 'faker', '~> 1.6', '>= 1.6.6'
gem 'foreman', '~> 0.87.0'
gem 'gmail', '~> 0.6.0'
gem 'jdbc-mysql', '8.0.17'
gem 'mysql2', '0.5.3'
gem 'parallel_tests'
gem 'pry', '~> 0.12.2'
gem 'rake'
gem 'report_builder'
gem 'rest-client'
gem 'rspec'
gem 'rspec-expectations', '~> 3.5.0'
gem 'selenium-cucumber'
gem 'selenium-webdriver'
gem 'sequel', '5.38.0'
